version: '3.8'

services:
  frontend:
    build: .
    container_name: qc-frontend
    image: nginx:latest # image untuk frontend  
    ports:
      - "823:823"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    networks:
      - qc-network

networks:
  qc-network:
    external: true